name: myst_app
description: A new Flutter project to display Hypixel SkyBlock profiles using the SkyCrypt API.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0

  # Add the http package for making HTTP requests
  http: ^0.13.3
  intl: ^0.18.0
  carousel_slider: ^4.0.0  # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Minecraftia
      fonts:
        - asset: assets/fonts/Minecraftia.ttf

